### ISSUE TITLE
Add Orb by Memgraph to list of libraries

### ISSUE THREAD

**Issue by kgolubic** [anvaka/graph-drawing-libraries#29]
Can you add Orb to your list of libraries? Repo is located at [https://github.com/memgraph/orb](https://github.com/memgraph/orb), and the backstory is available in the blog post at [https://memgraph.com/blog/how-to-build-a-graph-visualization-engine-and-why-you-shouldnt](https://memgraph.com/blog/how-to-build-a-graph-visualization-engine-and-why-you-shouldnt).

**Comment by anvaka** [comment]
Added here: https://github.com/anvaka/graph-drawing-libraries/commit/2e20a8d01d7db916f5ad7ed32b7be816220ecb39 Please feel free to send a PR if you want to provide a demo, similar to those in https://github.com/anvaka/graph-drawing-libraries/tree/main/v2
