### ISSUE TITLE
Add linkurious.js

### ISSUE THREAD

**Issue by jvilledieu** [anvaka/graph-drawing-libraries#9]
https://github.com/Linkurious/linkurious.js

**Comment by anvaka** [comment]
Isn't it the same as sigma?

**Comment by jvilledieu** [comment]
It's a set of plugins that augment sigma with new functionalities.

**Comment by anvaka** [comment]
Thank you. Added in https://github.com/anvaka/graph-drawing-libraries/commit/36ff763b6096450c19dd16a40415032e767f9635

I think it would also make sense to add it to this collection http://www.jsgraphs.com/
